### ISSUE TITLE
NCList.getRegionsInRange buggy?

### ISSUE THREAD

**Issue by gmungoc** [paulbible/papst#1]
Just cloned from github and wrote the attached unit test which fails.
Create an NCList with regions 100-500 and 200-300.
getRegionsInRange(400, 600) returns both ranges.
getRegionsInRange() adds all sub-regions of an overlapping region, without checking whether they also overlap the target range.

[NCListTest.java.txt](https://github.com/paulbible/papst/files/847781/NCListTest.java.txt)

**Comment by paulbible** [comment]
Hi, thanks for the minimal test data. I will take a look as soon as I can.

**Comment by gmungoc** [comment]
Another failing test added (unless I am misunderstanding how to use this class).
Create an NCList with regions 100-400 and 200-500.
getRegionsInRange(300, 300) returns the first range only.
[NCListTest.java.txt](https://github.com/paulbible/papst/files/848038/NCListTest.java.txt)

**Comment by paulbible** [comment]
Hi gmungoc, thank you for your help. There were indeed some bugs in the corner cases of the data structure. I have implemented a fix and your tests are now working. Let me know if you run into any other issues.

thanks,
Paul
